In [ ]:
import sys
import os

# Get the directory containing the notebook
NOTEBOOK_DIR = os.getcwd()

# Compute project root (go up one level)
PROJECT_ROOT = os.path.abspath(os.path.join(NOTEBOOK_DIR, '..'))

# Add project root to path
if PROJECT_ROOT not in sys.path:
    sys.path.append(PROJECT_ROOT)

print(sys.path)


### Latent Space Analysis

In [5]:
import matplotlib.pyplot as plt
import numpy as np
import os

from src.visualization.helpers import split_embeddings
# from src.visualization.visualization_functions import visualize_poincare_from_lorentz, compute_umap

In [ ]:
import scanpy as sc
adata = sc.read_loom("/Users/jeromecho/Library/CloudStorage/OneDrive-Personal/Thesis/code/liver_time.loom")

In [ ]:
zonation_genes_mouse_path = "/Users/jeromecho/Library/CloudStorage/OneDrive-Personal/Thesis/code/CellUntangler/genes/zonation_genes_mouse.tsv"
zonation_genes_mouse = pd.read_csv(zonation_genes_mouse_path, header=None, sep="\t")

In [6]:
embeddings_save_path = "./experiments/liver_zonation_repro/oct_6"
model_name = "e2, e10"
# Load in the embeddings
# Q: What does "v63" mean in the context of the below? 
embeddings = np.loadtxt(os.path.join(embeddings_save_path, f'{model_name}_all_encode_v63_z_params.txt'))

In [7]:
embeddings

array([[-6.26882375e-02,  4.15899817e-03, -3.89413734e-02, ...,
         8.27718875e-03, -1.20444976e-03, -4.41150127e-03],
       [-5.85523629e-01,  4.02100141e-03,  7.85161668e-01, ...,
         1.75882136e-02, -6.17995997e-03, -1.60814372e-02],
       [-1.67598353e+00,  1.45466562e-02,  5.97405364e-01, ...,
         1.81052276e-02, -4.13021985e-03, -1.68690948e-02],
       ...,
       [-9.60099215e-01,  8.31492060e-03,  2.63319845e-01, ...,
         1.74478655e-02,  6.28639986e-03, -8.99514823e-03],
       [-7.44783152e-01,  5.45689098e-03,  8.91169340e-01, ...,
         1.09502510e-02, -1.78360400e-03, -1.00482695e-02],
       [-7.78604785e-01,  7.33733433e-03,  4.38675169e-01, ...,
         1.66928357e-02,  2.31560425e-03, -7.52414736e-03]],
      shape=(7212, 12))

In [8]:
# Returns a dictionary where the keys are of the format componenti_subspace
# E.g., e2, e10 would result in keys of component1_e2 and component2_e10
# The values are the corresponding embeddings
component_embeddings = split_embeddings(model_name, embeddings)
for c in component_embeddings:
    adata.obsm[c] = component_embeddings[c]

e2 2
e10 10


NameError: name 'adata' is not defined

In [18]:
component_embeddings

{'component1_e2': array([[-0.06268824,  0.004159  ],
        [-0.58552363,  0.004021  ],
        [-1.67598353,  0.01454666],
        ...,
        [-0.96009922,  0.00831492],
        [-0.74478315,  0.00545689],
        [-0.77860478,  0.00733733]], shape=(7212, 2)),
 'component2_e10': array([[-0.03894137,  0.00274753,  0.01237631, ...,  0.00827719,
         -0.00120445, -0.0044115 ],
        [ 0.78516167, -0.00511617,  0.01376458, ...,  0.01758821,
         -0.00617996, -0.01608144],
        [ 0.59740536, -0.00523309,  0.00997876, ...,  0.01810523,
         -0.00413022, -0.01686909],
        ...,
        [ 0.26331984,  0.00386435,  0.00646384, ...,  0.01744787,
          0.0062864 , -0.00899515],
        [ 0.89116934,  0.00428178,  0.00953968, ...,  0.01095025,
         -0.0017836 , -0.01004827],
        [ 0.43867517,  0.00460109,  0.0060022 , ...,  0.01669284,
          0.0023156 , -0.00752415]], shape=(7212, 10))}

In [19]:
adata.obsm["component1_e2"]

array([[-0.06268824,  0.004159  ],
       [-0.58552363,  0.004021  ],
       [-1.67598353,  0.01454666],
       ...,
       [-0.96009922,  0.00831492],
       [-0.74478315,  0.00545689],
       [-0.77860478,  0.00733733]], shape=(7212, 2))

In [21]:
adata.obsm["component2_e10"]

array([[-0.03894137,  0.00274753,  0.01237631, ...,  0.00827719,
        -0.00120445, -0.0044115 ],
       [ 0.78516167, -0.00511617,  0.01376458, ...,  0.01758821,
        -0.00617996, -0.01608144],
       [ 0.59740536, -0.00523309,  0.00997876, ...,  0.01810523,
        -0.00413022, -0.01686909],
       ...,
       [ 0.26331984,  0.00386435,  0.00646384, ...,  0.01744787,
         0.0062864 , -0.00899515],
       [ 0.89116934,  0.00428178,  0.00953968, ...,  0.01095025,
        -0.0017836 , -0.01004827],
       [ 0.43867517,  0.00460109,  0.0060022 , ...,  0.01669284,
         0.0023156 , -0.00752415]], shape=(7212, 10))

### Inter-subspace Mutual Information

### Intra-subspace Mutual Information